name: ldc
channels:
  - conda-forge
  - patrikhlobil
  - defaults
dependencies:
  - geopandas
  - plotly
  - streamlit
  - pandas-stubs
  - pandas-bokeh
  
  - pip
  - pip:
    - streamlit-bokeh-events
